import random
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework import status

# Pre-canned task templates for specific prompts to make the UI feel highly intelligent and responsive out of the box
AI_TEMPLATES = {
    "auth": [
        {"title": "Setup JWT Authentication endpoints in Django", "description": "Configure SimpleJWT settings, create views for login, register, token refresh, and profile retrieval.", "priority": "high", "status": "todo"},
        {"title": "Create React Auth State Store using Zustand", "description": "Implement useAuthStore to handle tokens, storage, user session, and initial load validation.", "priority": "high", "status": "todo"},
        {"title": "Implement Axios client interceptors for token auto-refresh", "description": "Detect 401 errors, request new token using refresh token, and transparently retry original request.", "priority": "medium", "status": "todo"},
        {"title": "Build Login and Register UI screens", "description": "Create responsive views using react-hook-form and Zod validation. Handle field validations and server-side errors.", "priority": "high", "status": "todo"},
        {"title": "Write unit tests for authentication views", "description": "Write pytest checks for login, register, profile fetching, and token refresh.", "priority": "low", "status": "todo"}
    ],
    "deploy": [
        {"title": "Configure multi-stage Dockerfiles for Django and React", "description": "Create Dockerfile.dev and production Dockerfiles optimized for layer caching.", "priority": "high", "status": "todo"},
        {"title": "Setup docker-compose for PostgreSQL, Redis, Django, and React", "description": "Configure networks, volumes, healthchecks, and service environment variables.", "priority": "high", "status": "todo"},
        {"title": "Configure Nginx reverse proxy configuration", "description": "Setup routing rules for /api/ vs frontend static files, configure SSL certificates.", "priority": "medium", "status": "todo"},
        {"title": "Setup CI/CD deployment workflow", "description": "Configure GitHub Actions or GitLab CI to build docker images, run tests, and deploy to server.", "priority": "medium", "status": "todo"}
    ],
    "database": [
        {"title": "Design PostgreSQL database schema & migrations", "description": "Define models for User, Project, Task, and relationships. Run makemigrations.", "priority": "high", "status": "todo"},
        {"title": "Setup database connection pooling with django-db-conn-pool or PgBouncer", "description": "Configure DB pool limits to prevent connection exhaustion under high load.", "priority": "medium", "status": "todo"},
        {"title": "Create database backup and recovery cron scripts", "description": "Configure automatic nightly pg_dump backups uploaded to secure AWS S3 bucket.", "priority": "low", "status": "todo"}
    ],
    "ai": [
        {"title": "Integrate LLM API Provider (Gemini/OpenAI) in backend", "description": "Implement AI helper client with retry logic, rate-limit handling, and prompt template formatting.", "priority": "high", "status": "todo"},
        {"title": "Create Copilot chat interface in React dashboard", "description": "Construct chatbot component with typing statuses, custom commands, and action buttons.", "priority": "medium", "status": "todo"},
        {"title": "Add bulk task insertion API in Tasks viewset", "description": "Allow passing a list of tasks generated by AI and saving them in a single transaction database commit.", "priority": "high", "status": "todo"}
    ]
}

GENERIC_VERBS = ["Design", "Implement", "Refactor", "Build", "Review", "Test", "Deploy"]
GENERIC_NOUNS = ["UI Components", "REST API integration", "state management logic", "caching layers using Redis", "performance monitoring checks", "error boundary handlers"]

class AICopilotView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request, *args, **kwargs):
        prompt = request.data.get("prompt", "").lower()
        project_id = request.data.get("project_id")

        if not prompt:
            return Response(
                {"error": "Prompt field is required"}, 
                status=status.HTTP_400_BAD_REQUEST
            )

        # Match prompt with pre-canned templates
        suggested_tasks = []
        for key, templates in AI_TEMPLATES.items():
            if key in prompt:
                suggested_tasks = templates.copy()
                break

        # If no specific template matches, generate a dynamically styled task list
        if not suggested_tasks:
            # Generate 3 random smart tasks based on words from user prompt
            words = [w for w in prompt.split() if len(w) > 4]
            keyword = words[0] if words else "feature"
            
            suggested_tasks = [
                {
                    "title": f"Create outline architecture for {keyword.capitalize()}",
                    "description": f"Draft technical requirements and documentation for implementing '{prompt}' inside the workspace.",
                    "priority": "high",
                    "status": "todo"
                },
                {
                    "title": f"Implement core {keyword} code module",
                    "description": f"Write unit tests and main business logic to address request: '{prompt}'.",
                    "priority": "medium",
                    "status": "todo"
                },
                {
                    "title": f"Perform code review and testing for {keyword}",
                    "description": f"Validate coverage metrics, check security considerations, and verify API responses.",
                    "priority": "low",
                    "status": "todo"
                }
            ]

        # Inject project ID if provided
        for task in suggested_tasks:
            if project_id:
                task["project"] = project_id

        # Simulating LLM response wrapper
        ai_response = {
            "message": f"Hello! I've analyzed your prompt: '{prompt}'. Here are some recommended tasks to help you achieve this:",
            "suggestions": suggested_tasks,
            "tokens_used": random.randint(150, 400),
            "model": "gemini-3.5-flash-preview"
        }

        return Response(ai_response, status=status.HTTP_200_OK)
